/** @format */

import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Nate`s Portfolio</title>
        <meta name='description' content='Generated by Nate Burugu' />
      </Head>
      {/* Header */}
      <Header />

      {/* Hero   */}
      {/* about */}
      {/* Experience */}
      {/* skills */}
      {/* Project */}
      {/* Contact me */}
    </div>
  );
};

export default Home;
